repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: debug-statements
      - id: trailing-whitespace
      - id: check-ast
      - id: check-toml
      - id: requirements-txt-fixer
      - id: no-commit-to-branch   # this hook will protect to push changes directly in your main/master branch ( instead use MR/PR )
        args: [--branch, master, --branch, main]

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-pyproject]

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.0
    hooks:
      - id: autoflake
        args:
          [
            "--in-place",
            "--remove-unused-variables",
            "--remove-all-unused-imports",
            "--recursive",
            "--exclude=venv/",
        #"--expand-star-imports",
            "--ignore-init-module-imports",
            "--remove-duplicate-keys"
          ]
